### PR TITLE
Master

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
?

**Comment by yajo** [comment]
It was too outdated and updating from local was taking forever. It's faster to PR, merge, and then force push.

**Comment by pedrobaeza** [comment]
Except that this can waste commit history unless you use rebase option. Did you use it?

**Comment by yajo** [comment]
I force pushed, yes.

**Pull request merged**
